// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="uart2axi_uart2axi,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.650000,HLS_SYN_LAT=526,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=1239,HLS_SYN_LUT=4560,HLS_VERSION=2022_2}" *)

module uart2axi (
        ap_clk,
        ap_rst_n,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        rx_data_dout,
        rx_data_empty_n,
        rx_data_read,
        tx_data_din,
        tx_data_full_n,
        tx_data_write,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER
);

parameter    ap_ST_fsm_state1 = 19'd1;
parameter    ap_ST_fsm_state2 = 19'd2;
parameter    ap_ST_fsm_state3 = 19'd4;
parameter    ap_ST_fsm_state4 = 19'd8;
parameter    ap_ST_fsm_state5 = 19'd16;
parameter    ap_ST_fsm_state6 = 19'd32;
parameter    ap_ST_fsm_state7 = 19'd64;
parameter    ap_ST_fsm_state8 = 19'd128;
parameter    ap_ST_fsm_state9 = 19'd256;
parameter    ap_ST_fsm_state10 = 19'd512;
parameter    ap_ST_fsm_state11 = 19'd1024;
parameter    ap_ST_fsm_state12 = 19'd2048;
parameter    ap_ST_fsm_state13 = 19'd4096;
parameter    ap_ST_fsm_state14 = 19'd8192;
parameter    ap_ST_fsm_state15 = 19'd16384;
parameter    ap_ST_fsm_state16 = 19'd32768;
parameter    ap_ST_fsm_state17 = 19'd65536;
parameter    ap_ST_fsm_state18 = 19'd131072;
parameter    ap_ST_fsm_state19 = 19'd262144;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_TARGET_ADDR = 0;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] rx_data_dout;
input   rx_data_empty_n;
output   rx_data_read;
output  [7:0] tx_data_din;
input   tx_data_full_n;
output   tx_data_write;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg rx_data_read;
reg[7:0] tx_data_din;
reg tx_data_write;

 reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [18:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    rx_data_blk_n;
wire   [0:0] tmp_nbreadreq_fu_80_p3;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
reg   [7:0] reg_156;
reg   [0:0] tmp_reg_198;
wire   [0:0] icmp_ln1019_fu_164_p2;
reg   [0:0] icmp_ln1019_reg_202;
reg   [7:0] u8_temp_V_1_reg_206;
reg   [7:0] u8_temp_V_2_reg_211;
reg   [7:0] u8_temp_V_3_reg_216;
wire   [31:0] addr_V_fu_170_p5;
reg   [31:0] addr_V_reg_221;
wire   [10:0] mul_i_i_fu_190_p3;
reg   [10:0] mul_i_i_reg_227;
reg   [8:0] uart_buffer_V_address0;
reg    uart_buffer_V_ce0;
reg    uart_buffer_V_we0;
reg   [7:0] uart_buffer_V_d0;
wire   [7:0] uart_buffer_V_q0;
reg   [8:0] uart_buffer_V_address1;
reg    uart_buffer_V_ce1;
reg    uart_buffer_V_we1;
wire   [7:0] uart_buffer_V_q1;
reg   [8:0] uart_buffer_V_1_address0;
reg    uart_buffer_V_1_ce0;
reg    uart_buffer_V_1_we0;
reg   [7:0] uart_buffer_V_1_d0;
wire   [7:0] uart_buffer_V_1_q0;
reg   [8:0] uart_buffer_V_1_address1;
reg    uart_buffer_V_1_ce1;
reg    uart_buffer_V_1_we1;
wire   [7:0] uart_buffer_V_1_q1;
reg   [7:0] axi_temp_V_address0;
reg    axi_temp_V_ce0;
reg    axi_temp_V_we0;
reg   [31:0] axi_temp_V_d0;
wire   [31:0] axi_temp_V_q0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_start;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_done;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_idle;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_ready;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWVALID;
wire   [63:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWADDR;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWID;
wire   [31:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWLEN;
wire   [2:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWSIZE;
wire   [1:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWBURST;
wire   [1:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWLOCK;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWCACHE;
wire   [2:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWPROT;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWQOS;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWREGION;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWUSER;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WVALID;
wire   [31:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WDATA;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WSTRB;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WLAST;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WID;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WUSER;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARVALID;
wire   [63:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARADDR;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARID;
wire   [31:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARLEN;
wire   [2:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARSIZE;
wire   [1:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARBURST;
wire   [1:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARLOCK;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARCACHE;
wire   [2:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARPROT;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARQOS;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARREGION;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARUSER;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_RREADY;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_BREADY;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_ce0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_we0;
wire   [31:0] grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_d0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_start;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_done;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_idle;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_ready;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_rx_data_read;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_ce0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_we0;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_d0;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_ce0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_we0;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_d0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_start;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_done;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_idle;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_ready;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_ce0;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_address1;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_ce1;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_ce0;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_address1;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_ce1;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_ce0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_we0;
wire   [31:0] grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_d0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_start;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_done;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_idle;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_ready;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWVALID;
wire   [63:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWADDR;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWID;
wire   [31:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWLEN;
wire   [2:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWSIZE;
wire   [1:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWBURST;
wire   [1:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWLOCK;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWCACHE;
wire   [2:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWPROT;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWQOS;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWREGION;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWUSER;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WVALID;
wire   [31:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WDATA;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WSTRB;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WLAST;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WID;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WUSER;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARVALID;
wire   [63:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARADDR;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARID;
wire   [31:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARLEN;
wire   [2:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARSIZE;
wire   [1:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARBURST;
wire   [1:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARLOCK;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARCACHE;
wire   [2:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARPROT;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARQOS;
wire   [3:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARREGION;
wire   [0:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARUSER;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_RREADY;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_BREADY;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_axi_temp_V_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_axi_temp_V_ce0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_start;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_done;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_idle;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_ready;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_tx_data_din;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_tx_data_write;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_ce0;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_1_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_1_ce0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_start;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_done;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_idle;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_ready;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_axi_temp_V_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_axi_temp_V_ce0;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_ce0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_we0;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_d0;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_address1;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_ce1;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_we1;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_d1;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_ce0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_we0;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_d0;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_address1;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_ce1;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_we1;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_d1;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_start;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_done;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_idle;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_ready;
wire   [7:0] grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_tx_data_din;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_tx_data_write;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_ce0;
wire   [8:0] grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_1_address0;
wire    grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_1_ce0;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [12:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg    grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_start_reg;
wire    ap_CS_fsm_state15;
reg    grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg    grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_start_reg;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
reg    grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_start_reg;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
reg    ap_block_state1;
wire   [8:0] burst_len_V_cast_fu_180_p1;
wire   [8:0] add_i_i599_fu_184_p2;
reg    ap_predicate_op55_call_state14;
reg    ap_block_state14_on_subcall_done;
reg   [18:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
reg    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
reg    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
reg    ap_ST_fsm_state19_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 19'd1;
#0 grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_start_reg = 1'b0;
#0 grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_start_reg = 1'b0;
#0 grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_start_reg = 1'b0;
#0 grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_start_reg = 1'b0;
#0 grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_start_reg = 1'b0;
#0 grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_start_reg = 1'b0;
#0 grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_start_reg = 1'b0;
end

uart2axi_uart_buffer_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
uart_buffer_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(uart_buffer_V_address0),
    .ce0(uart_buffer_V_ce0),
    .we0(uart_buffer_V_we0),
    .d0(uart_buffer_V_d0),
    .q0(uart_buffer_V_q0),
    .address1(uart_buffer_V_address1),
    .ce1(uart_buffer_V_ce1),
    .we1(uart_buffer_V_we1),
    .d1(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_d1),
    .q1(uart_buffer_V_q1)
);

uart2axi_uart_buffer_V_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
uart_buffer_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(uart_buffer_V_1_address0),
    .ce0(uart_buffer_V_1_ce0),
    .we0(uart_buffer_V_1_we0),
    .d0(uart_buffer_V_1_d0),
    .q0(uart_buffer_V_1_q0),
    .address1(uart_buffer_V_1_address1),
    .ce1(uart_buffer_V_1_ce1),
    .we1(uart_buffer_V_1_we1),
    .d1(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_d1),
    .q1(uart_buffer_V_1_q1)
);

uart2axi_axi_temp_V_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
axi_temp_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(axi_temp_V_address0),
    .ce0(axi_temp_V_ce0),
    .we0(axi_temp_V_we0),
    .d0(axi_temp_V_d0),
    .q0(axi_temp_V_q0)
);

uart2axi_uart2axi_Pipeline_VITIS_LOOP_41_1 grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_start),
    .ap_done(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_done),
    .ap_idle(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_idle),
    .ap_ready(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_ready),
    .m_axi_gmem_AWVALID(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .lhs_V(addr_V_reg_221),
    .axi_temp_V_address0(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_address0),
    .axi_temp_V_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_ce0),
    .axi_temp_V_we0(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_we0),
    .axi_temp_V_d0(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_d0),
    .burst_len_V(reg_156)
);

uart2axi_uart2axi_Pipeline_VITIS_LOOP_63_4 grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_start),
    .ap_done(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_done),
    .ap_idle(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_idle),
    .ap_ready(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_ready),
    .rx_data_dout(rx_data_dout),
    .rx_data_empty_n(rx_data_empty_n),
    .rx_data_read(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_rx_data_read),
    .uart_buffer_V_address0(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_address0),
    .uart_buffer_V_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_ce0),
    .uart_buffer_V_we0(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_we0),
    .uart_buffer_V_d0(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_d0),
    .uart_buffer_V_1_address0(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_address0),
    .uart_buffer_V_1_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_ce0),
    .uart_buffer_V_1_we0(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_we0),
    .uart_buffer_V_1_d0(grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_d0),
    .mul_i_i(mul_i_i_reg_227)
);

uart2axi_uart2axi_Pipeline_VITIS_LOOP_69_5 grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_start),
    .ap_done(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_done),
    .ap_idle(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_idle),
    .ap_ready(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_ready),
    .uart_buffer_V_address0(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_address0),
    .uart_buffer_V_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_ce0),
    .uart_buffer_V_q0(uart_buffer_V_q0),
    .uart_buffer_V_address1(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_address1),
    .uart_buffer_V_ce1(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_ce1),
    .uart_buffer_V_q1(uart_buffer_V_q1),
    .uart_buffer_V_1_address0(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_address0),
    .uart_buffer_V_1_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_ce0),
    .uart_buffer_V_1_q0(uart_buffer_V_1_q0),
    .uart_buffer_V_1_address1(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_address1),
    .uart_buffer_V_1_ce1(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_ce1),
    .uart_buffer_V_1_q1(uart_buffer_V_1_q1),
    .axi_temp_V_address0(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_address0),
    .axi_temp_V_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_ce0),
    .axi_temp_V_we0(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_we0),
    .axi_temp_V_d0(grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_d0),
    .burst_len_V(reg_156)
);

uart2axi_uart2axi_Pipeline_VITIS_LOOP_78_6 grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_start),
    .ap_done(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_done),
    .ap_idle(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_idle),
    .ap_ready(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_ready),
    .m_axi_gmem_AWVALID(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(32'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(13'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .axi_temp_V_address0(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_axi_temp_V_address0),
    .axi_temp_V_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_axi_temp_V_ce0),
    .axi_temp_V_q0(axi_temp_V_q0),
    .lhs_V(addr_V_reg_221),
    .burst_len_V(reg_156)
);

uart2axi_uart2axi_Pipeline_VITIS_LOOP_84_7 grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_start),
    .ap_done(grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_done),
    .ap_idle(grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_idle),
    .ap_ready(grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_ready),
    .tx_data_din(grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_tx_data_din),
    .tx_data_full_n(tx_data_full_n),
    .tx_data_write(grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_tx_data_write),
    .uart_buffer_V_address0(grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_address0),
    .uart_buffer_V_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_ce0),
    .uart_buffer_V_q0(uart_buffer_V_q0),
    .uart_buffer_V_1_address0(grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_1_address0),
    .uart_buffer_V_1_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_1_ce0),
    .uart_buffer_V_1_q0(uart_buffer_V_1_q0),
    .mul_i_i(mul_i_i_reg_227)
);

uart2axi_uart2axi_Pipeline_VITIS_LOOP_47_2 grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_start),
    .ap_done(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_done),
    .ap_idle(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_idle),
    .ap_ready(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_ready),
    .axi_temp_V_address0(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_axi_temp_V_address0),
    .axi_temp_V_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_axi_temp_V_ce0),
    .axi_temp_V_q0(axi_temp_V_q0),
    .uart_buffer_V_address0(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_address0),
    .uart_buffer_V_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_ce0),
    .uart_buffer_V_we0(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_we0),
    .uart_buffer_V_d0(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_d0),
    .uart_buffer_V_address1(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_address1),
    .uart_buffer_V_ce1(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_ce1),
    .uart_buffer_V_we1(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_we1),
    .uart_buffer_V_d1(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_d1),
    .uart_buffer_V_1_address0(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_address0),
    .uart_buffer_V_1_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_ce0),
    .uart_buffer_V_1_we0(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_we0),
    .uart_buffer_V_1_d0(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_d0),
    .uart_buffer_V_1_address1(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_address1),
    .uart_buffer_V_1_ce1(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_ce1),
    .uart_buffer_V_1_we1(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_we1),
    .uart_buffer_V_1_d1(grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_d1),
    .burst_len_V(reg_156)
);

uart2axi_uart2axi_Pipeline_VITIS_LOOP_56_3 grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_start),
    .ap_done(grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_done),
    .ap_idle(grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_idle),
    .ap_ready(grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_ready),
    .tx_data_din(grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_tx_data_din),
    .tx_data_full_n(tx_data_full_n),
    .tx_data_write(grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_tx_data_write),
    .uart_buffer_V_address0(grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_address0),
    .uart_buffer_V_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_ce0),
    .uart_buffer_V_q0(uart_buffer_V_q0),
    .uart_buffer_V_1_address0(grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_1_address0),
    .uart_buffer_V_1_ce0(grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_1_ce0),
    .uart_buffer_V_1_q0(uart_buffer_V_1_q0),
    .mul_i_i(mul_i_i_reg_227)
);

uart2axi_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 5 ),
    .MAX_READ_BURST_LENGTH( 256 ),
    .MAX_WRITE_BURST_LENGTH( 256 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_TARGET_ADDR( C_M_AXI_GMEM_TARGET_ADDR ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 13 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARADDR),
    .I_ARLEN(grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWADDR),
    .I_AWLEN(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWLEN),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WDATA),
    .I_WSTRB(grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_start_reg <= 1'b0;
    end else begin
        if (((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln1019_reg_202 == 1'd1))) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_start_reg <= 1'b1;
        end else if ((grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_ready == 1'b1)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state16)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_start_reg <= 1'b1;
        end else if ((grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_ready == 1'b1)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state18)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_start_reg <= 1'b1;
        end else if ((grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_ready == 1'b1)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_start_reg <= 1'b1;
        end else if ((grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_ready == 1'b1)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_start_reg <= 1'b1;
        end else if ((grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_ready == 1'b1)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_start_reg <= 1'b1;
        end else if ((grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_ready == 1'b1)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_ready == 1'b1)) begin
            grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        addr_V_reg_221 <= addr_V_fu_170_p5;
        mul_i_i_reg_227[10 : 2] <= mul_i_i_fu_190_p3[10 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_80_p3 == 1'd1))) begin
        icmp_ln1019_reg_202 <= icmp_ln1019_fu_164_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        reg_156 <= rx_data_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_reg_198 <= tmp_nbreadreq_fu_80_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        u8_temp_V_1_reg_206 <= rx_data_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        u8_temp_V_2_reg_211 <= rx_data_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        u8_temp_V_3_reg_216 <= rx_data_dout;
    end
end

always @ (*) begin
    if ((grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state14_on_subcall_done)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_done == 1'b0)) begin
        ap_ST_fsm_state15_blk = 1'b1;
    end else begin
        ap_ST_fsm_state15_blk = 1'b0;
    end
end

assign ap_ST_fsm_state16_blk = 1'b0;

always @ (*) begin
    if ((grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_done == 1'b0)) begin
        ap_ST_fsm_state17_blk = 1'b1;
    end else begin
        ap_ST_fsm_state17_blk = 1'b0;
    end
end

assign ap_ST_fsm_state18_blk = 1'b0;

always @ (*) begin
    if ((grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_done == 1'b0)) begin
        ap_ST_fsm_state19_blk = 1'b1;
    end else begin
        ap_ST_fsm_state19_blk = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | ((rx_data_empty_n == 1'b0) & (tmp_nbreadreq_fu_80_p3 == 1'd1)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((rx_data_empty_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((rx_data_empty_n == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((rx_data_empty_n == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((rx_data_empty_n == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((rx_data_empty_n == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b0 == ap_block_state14_on_subcall_done) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state14_on_subcall_done) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        axi_temp_V_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_axi_temp_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        axi_temp_V_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_axi_temp_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_temp_V_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        axi_temp_V_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_address0;
    end else begin
        axi_temp_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        axi_temp_V_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_axi_temp_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        axi_temp_V_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_axi_temp_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_temp_V_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        axi_temp_V_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_ce0;
    end else begin
        axi_temp_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_temp_V_d0 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        axi_temp_V_d0 = grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_d0;
    end else begin
        axi_temp_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        axi_temp_V_we0 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_axi_temp_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        axi_temp_V_we0 = grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_axi_temp_V_we0;
    end else begin
        axi_temp_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln1019_reg_202 == 1'd1)))) begin
        gmem_ARVALID = grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_AWVALID = grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_BREADY = grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state15) | ((1'b1 == ap_CS_fsm_state6) & (icmp_ln1019_reg_202 == 1'd1)))) begin
        gmem_RREADY = grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11))) begin
        gmem_WVALID = grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_80_p3 == 1'd1)))) begin
        rx_data_blk_n = rx_data_empty_n;
    end else begin
        rx_data_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((ap_start == 1'b0) | ((rx_data_empty_n == 1'b0) & (tmp_nbreadreq_fu_80_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_80_p3 == 1'd1)) | ((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6)) | ((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5)) | ((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        rx_data_read = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        rx_data_read = grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_rx_data_read;
    end else begin
        rx_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        tx_data_din = grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_tx_data_din;
    end else if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln1019_reg_202 == 1'd0) & (tmp_reg_198 == 1'd1))) begin
        tx_data_din = grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_tx_data_din;
    end else begin
        tx_data_din = grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_tx_data_din;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        tx_data_write = grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_tx_data_write;
    end else if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln1019_reg_202 == 1'd0) & (tmp_reg_198 == 1'd1))) begin
        tx_data_write = grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_tx_data_write;
    end else begin
        tx_data_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        uart_buffer_V_1_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_1_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_address0;
    end else if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln1019_reg_202 == 1'd0) & (tmp_reg_198 == 1'd1))) begin
        uart_buffer_V_1_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        uart_buffer_V_1_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        uart_buffer_V_1_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_address0;
    end else begin
        uart_buffer_V_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_1_address1 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        uart_buffer_V_1_address1 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_address1;
    end else begin
        uart_buffer_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        uart_buffer_V_1_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_1_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_ce0;
    end else if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln1019_reg_202 == 1'd0) & (tmp_reg_198 == 1'd1))) begin
        uart_buffer_V_1_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        uart_buffer_V_1_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        uart_buffer_V_1_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_ce0;
    end else begin
        uart_buffer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_1_ce1 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        uart_buffer_V_1_ce1 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_1_ce1;
    end else begin
        uart_buffer_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_1_d0 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        uart_buffer_V_1_d0 = grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_d0;
    end else begin
        uart_buffer_V_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_1_we0 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        uart_buffer_V_1_we0 = grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_1_we0;
    end else begin
        uart_buffer_V_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_1_we1 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_1_we1;
    end else begin
        uart_buffer_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        uart_buffer_V_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_address0;
    end else if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln1019_reg_202 == 1'd0) & (tmp_reg_198 == 1'd1))) begin
        uart_buffer_V_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        uart_buffer_V_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        uart_buffer_V_address0 = grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_address0;
    end else begin
        uart_buffer_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_address1 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        uart_buffer_V_address1 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_address1;
    end else begin
        uart_buffer_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        uart_buffer_V_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_uart_buffer_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_ce0;
    end else if (((1'b1 == ap_CS_fsm_state14) & (icmp_ln1019_reg_202 == 1'd0) & (tmp_reg_198 == 1'd1))) begin
        uart_buffer_V_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_uart_buffer_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        uart_buffer_V_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        uart_buffer_V_ce0 = grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_ce0;
    end else begin
        uart_buffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_ce1 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        uart_buffer_V_ce1 = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_uart_buffer_V_ce1;
    end else begin
        uart_buffer_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_d0 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        uart_buffer_V_d0 = grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_d0;
    end else begin
        uart_buffer_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_we0 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        uart_buffer_V_we0 = grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_uart_buffer_V_we0;
    end else begin
        uart_buffer_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        uart_buffer_V_we1 = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_uart_buffer_V_we1;
    end else begin
        uart_buffer_V_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | ((rx_data_empty_n == 1'b0) & (tmp_nbreadreq_fu_80_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_80_p3 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else if ((~((ap_start == 1'b0) | ((rx_data_empty_n == 1'b0) & (tmp_nbreadreq_fu_80_p3 == 1'd1))) & (1'b1 == ap_CS_fsm_state1) & (tmp_nbreadreq_fu_80_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln1019_reg_202 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else if (((rx_data_empty_n == 1'b1) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln1019_reg_202 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b0 == ap_block_state14_on_subcall_done) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            if (((1'b1 == ap_CS_fsm_state15) & (grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            if (((grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state17))) begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            if (((grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state19))) begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_i_i599_fu_184_p2 = (burst_len_V_cast_fu_180_p1 + 9'd1);

assign addr_V_fu_170_p5 = {{{{reg_156}, {u8_temp_V_1_reg_206}}, {u8_temp_V_2_reg_211}}, {u8_temp_V_3_reg_216}};

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | ((rx_data_empty_n == 1'b0) & (tmp_nbreadreq_fu_80_p3 == 1'd1)));
end

always @ (*) begin
    ap_block_state14_on_subcall_done = ((ap_predicate_op55_call_state14 == 1'b1) & (grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_done == 1'b0));
end

always @ (*) begin
    ap_predicate_op55_call_state14 = ((icmp_ln1019_reg_202 == 1'd0) & (tmp_reg_198 == 1'd1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign burst_len_V_cast_fu_180_p1 = rx_data_dout;

assign grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_start = grp_uart2axi_Pipeline_VITIS_LOOP_41_1_fu_94_ap_start_reg;

assign grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_start = grp_uart2axi_Pipeline_VITIS_LOOP_47_2_fu_139_ap_start_reg;

assign grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_start = grp_uart2axi_Pipeline_VITIS_LOOP_56_3_fu_147_ap_start_reg;

assign grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_start = grp_uart2axi_Pipeline_VITIS_LOOP_63_4_fu_104_ap_start_reg;

assign grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_start = grp_uart2axi_Pipeline_VITIS_LOOP_69_5_fu_113_ap_start_reg;

assign grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_start = grp_uart2axi_Pipeline_VITIS_LOOP_78_6_fu_121_ap_start_reg;

assign grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_start = grp_uart2axi_Pipeline_VITIS_LOOP_84_7_fu_130_ap_start_reg;

assign icmp_ln1019_fu_164_p2 = ((rx_data_dout == 8'd0) ? 1'b1 : 1'b0);

assign mul_i_i_fu_190_p3 = {{add_i_i599_fu_184_p2}, {2'd0}};

assign tmp_nbreadreq_fu_80_p3 = rx_data_empty_n;

always @ (posedge ap_clk) begin
    mul_i_i_reg_227[1:0] <= 2'b00;
end

endmodule //uart2axi
