// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module uart2axi_uart2axi_Pipeline_VITIS_LOOP_69_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        uart_buffer_V_address0,
        uart_buffer_V_ce0,
        uart_buffer_V_q0,
        uart_buffer_V_address1,
        uart_buffer_V_ce1,
        uart_buffer_V_q1,
        uart_buffer_V_1_address0,
        uart_buffer_V_1_ce0,
        uart_buffer_V_1_q0,
        uart_buffer_V_1_address1,
        uart_buffer_V_1_ce1,
        uart_buffer_V_1_q1,
        axi_temp_V_address0,
        axi_temp_V_ce0,
        axi_temp_V_we0,
        axi_temp_V_d0,
        burst_len_V
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] uart_buffer_V_address0;
output   uart_buffer_V_ce0;
input  [7:0] uart_buffer_V_q0;
output  [8:0] uart_buffer_V_address1;
output   uart_buffer_V_ce1;
input  [7:0] uart_buffer_V_q1;
output  [8:0] uart_buffer_V_1_address0;
output   uart_buffer_V_1_ce0;
input  [7:0] uart_buffer_V_1_q0;
output  [8:0] uart_buffer_V_1_address1;
output   uart_buffer_V_1_ce1;
input  [7:0] uart_buffer_V_1_q1;
output  [7:0] axi_temp_V_address0;
output   axi_temp_V_ce0;
output   axi_temp_V_we0;
output  [31:0] axi_temp_V_d0;
input  [7:0] burst_len_V;

reg ap_idle;
reg uart_buffer_V_ce0;
reg uart_buffer_V_ce1;
reg uart_buffer_V_1_ce0;
reg uart_buffer_V_1_ce1;
reg axi_temp_V_ce0;
reg axi_temp_V_we0;

reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
wire   [0:0] icmp_ln1027_3_fu_147_p2;
wire   [0:0] icmp_ln1027_fu_127_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] icmp_ln1027_reg_204;
wire   [0:0] icmp_ln1027_reg_204_pp0_iter0_reg;
wire   [63:0] zext_ln1027_fu_139_p1;
reg   [63:0] zext_ln1027_reg_208;
reg   [0:0] icmp_ln1027_3_reg_213;
wire   [0:0] icmp_ln1027_3_reg_213_pp0_iter0_reg;
wire   [63:0] zext_ln72_fu_161_p1;
wire   [63:0] zext_ln74_fu_173_p1;
reg   [8:0] j_V_fu_46;
wire   [8:0] add_ln840_fu_133_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_j_V_2;
wire   [7:0] trunc_ln1027_fu_143_p1;
wire   [8:0] shl_ln1_fu_153_p3;
wire   [8:0] or_ln74_fu_167_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
end

uart2axi_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready == 1'b0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        if (((icmp_ln1027_fu_127_p2 == 1'd0) & (icmp_ln1027_3_fu_147_p2 == 1'd0))) begin
            j_V_fu_46 <= add_ln840_fu_133_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_V_fu_46 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_fu_127_p2 == 1'd0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        icmp_ln1027_3_reg_213 <= icmp_ln1027_3_fu_147_p2;
        zext_ln1027_reg_208[8 : 0] <= zext_ln1027_fu_139_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        icmp_ln1027_reg_204 <= icmp_ln1027_fu_127_p2;
    end
end

always @ (*) begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1) & ((icmp_ln1027_fu_127_p2 == 1'd1) | (icmp_ln1027_3_fu_147_p2 == 1'd1)))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_V_2 = 9'd0;
    end else begin
        ap_sig_allocacmp_j_V_2 = j_V_fu_46;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter1_fsm_state2)) begin
        axi_temp_V_ce0 = 1'b1;
    end else begin
        axi_temp_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1027_3_reg_213_pp0_iter0_reg == 1'd0) & (icmp_ln1027_reg_204_pp0_iter0_reg == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        axi_temp_V_we0 = 1'b1;
    end else begin
        axi_temp_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        uart_buffer_V_1_ce0 = 1'b1;
    end else begin
        uart_buffer_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        uart_buffer_V_1_ce1 = 1'b1;
    end else begin
        uart_buffer_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        uart_buffer_V_ce0 = 1'b1;
    end else begin
        uart_buffer_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
        uart_buffer_V_ce1 = 1'b1;
    end else begin
        uart_buffer_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if (((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b0)))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else if ((((1'b1 == ap_CS_iter1_fsm_state2) & ((icmp_ln1027_3_reg_213_pp0_iter0_reg == 1'd1) | (icmp_ln1027_reg_204_pp0_iter0_reg == 1'd1))) | ((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1)))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_start_int == 1'b1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln840_fu_133_p2 = (ap_sig_allocacmp_j_V_2 + 9'd1);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign axi_temp_V_address0 = zext_ln1027_reg_208;

assign axi_temp_V_d0 = {{{{uart_buffer_V_q1}, {uart_buffer_V_1_q1}}, {uart_buffer_V_q0}}, {uart_buffer_V_1_q0}};

assign icmp_ln1027_3_fu_147_p2 = ((burst_len_V < trunc_ln1027_fu_143_p1) ? 1'b1 : 1'b0);

assign icmp_ln1027_3_reg_213_pp0_iter0_reg = icmp_ln1027_3_reg_213;

assign icmp_ln1027_fu_127_p2 = ((ap_sig_allocacmp_j_V_2 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln1027_reg_204_pp0_iter0_reg = icmp_ln1027_reg_204;

assign or_ln74_fu_167_p2 = (shl_ln1_fu_153_p3 | 9'd1);

assign shl_ln1_fu_153_p3 = {{trunc_ln1027_fu_143_p1}, {1'd0}};

assign trunc_ln1027_fu_143_p1 = ap_sig_allocacmp_j_V_2[7:0];

assign uart_buffer_V_1_address0 = zext_ln74_fu_173_p1;

assign uart_buffer_V_1_address1 = zext_ln72_fu_161_p1;

assign uart_buffer_V_address0 = zext_ln74_fu_173_p1;

assign uart_buffer_V_address1 = zext_ln72_fu_161_p1;

assign zext_ln1027_fu_139_p1 = ap_sig_allocacmp_j_V_2;

assign zext_ln72_fu_161_p1 = shl_ln1_fu_153_p3;

assign zext_ln74_fu_173_p1 = or_ln74_fu_167_p2;

always @ (posedge ap_clk) begin
    zext_ln1027_reg_208[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
end

endmodule //uart2axi_uart2axi_Pipeline_VITIS_LOOP_69_5
